# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_raw.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import argparse
from DLC_for_WBFM.utils.projects.utils_project import load_config, safe_cd
from DLC_for_WBFM.gui.utils_gui import array2qt, get_cropped_frame
import pandas as pd
import sys
from pathlib import Path
import matplotlib
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg
from matplotlib.figure import Figure
import numpy as np
matplotlib.use('Qt5Agg')



class MplCanvas(FigureCanvasQTAgg):
    # See: https://www.learnpyqt.com/tutorials/plotting-matplotlib/
    def __init__(self, parent=None, width=15, height=10, dpi=100):
        self.fig = Figure(figsize=(width, height), dpi=dpi)
        self.axes = self.fig.add_subplot(111)
        super(MplCanvas, self).__init__(self.fig)


# class Ui_MainWindow(QtWidgets.QMainWindow):
class Ui_MainWindow(object):
    def setupUi(self, MainWindow, cfg, DEBUG):
        # super(MainWindow, self).__init__()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1084, 754)

        ########################
        # Load Configs
        ########################
        cfg = load_config(project_config)
        self.project_dir = Path(project_config).parent
        self.cfg = cfg
        traces_cfg = load_config(cfg['subfolder_configs']['traces'])
        self.traces_cfg = traces_cfg
        segment_cfg = load_config(cfg['subfolder_configs']['segmentation'])
        self.segment_cfg = segment_cfg
        # COMBAK: make user setting
        self.crop_sz = (1, 48, 48)
        # self.crop_sz = None
        # self.current_centroid = (1, 100, 100)
        start = cfg['dataset_params']['start_volume']
        end = start + cfg['dataset_params']['num_frames']
        self.x = list(range(start, end))
        ########################
        # Load Data
        ########################
        # For matplotlib
        # COMBAK: not just red
        red_traces_fname = traces_cfg['traces']['red']
        green_traces_fname = traces_cfg['traces']['green']
        if not DEBUG:
            # print(f"Read traces from {traces_fname}")
            self.red_traces = pd.read_hdf(red_traces_fname)
            self.green_traces = pd.read_hdf(green_traces_fname)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")

        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        ########################
        # Various selectors
        ########################
        # Neuron selector
        self.neuronSelector = QtWidgets.QComboBox(self.centralwidget)
        self.neuronSelector.setObjectName("neuronSelector")
        neuron_names = traces_cfg['traces']['neuron_names']
        [self.neuronSelector.addItem(name) for name in neuron_names]
        self.verticalLayout_5.addWidget(self.neuronSelector)
        self.neuronSelector.currentIndexChanged.connect(self.update_all_panels)
        # Frame (time) selector
        self.timeSelector = QtWidgets.QSpinBox(self.centralwidget)
        start = cfg['dataset_params']['start_volume']
        self.timeSelector.setMinimum(start)
        end = start + cfg['dataset_params']['num_frames']
        self.timeSelector.setMaximum(end)
        self.timeSelector.setObjectName("timeSelector")
        self.verticalLayout_5.addWidget(self.timeSelector)
        self.timeSelector.valueChanged.connect(self.update_all_panels)
        # Background selector
        self.backgroundSelector = QtWidgets.QSpinBox(self.centralwidget)
        self.backgroundSelector.setMinimum(0)
        self.backgroundSelector.setValue(15)
        self.backgroundSelector.setMaximum(100)
        self.backgroundSelector.setObjectName("backgroundSelector")
        self.verticalLayout_5.addWidget(self.backgroundSelector)
        self.backgroundSelector.valueChanged.connect(self.update_only_traces)
        # Trace (mode) selector
        self.modeSelector = QtWidgets.QComboBox(self.centralwidget)
        self.modeSelector.setObjectName("modeSelector")
        possible_modes = ['green', 'red']
        [self.modeSelector.addItem(m) for m in possible_modes]
        self.verticalLayout_5.addWidget(self.modeSelector)
        self.modeSelector.currentIndexChanged.connect(self.update_only_traces)
        # Crop selectors
        self.cropXSelector = QtWidgets.QSpinBox(self.centralwidget)
        self.cropXSelector.setMinimum(10)
        self.cropXSelector.setValue(64)
        self.cropXSelector.setSingleStep(16)
        self.cropXSelector.setMaximum(100)
        self.cropXSelector.setObjectName("cropXSelector")
        self.verticalLayout_5.addWidget(self.cropXSelector)
        self.cropXSelector.valueChanged.connect(self.update_all_panels)

        self.cropYSelector = QtWidgets.QSpinBox(self.centralwidget)
        self.cropYSelector.setMinimum(10)
        self.cropYSelector.setValue(64)
        self.cropYSelector.setSingleStep(16)
        self.cropYSelector.setMaximum(100)
        self.cropYSelector.setObjectName("cropYSelector")
        self.verticalLayout_5.addWidget(self.cropYSelector)
        self.cropYSelector.valueChanged.connect(self.update_all_panels)

        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        ########################
        # Traces (matplotlib)
        ########################
        sc = MplCanvas(self, width=15, height=4, dpi=100)
        self.tracesPlt = sc
        # sc.axes.plot([0,1,2,3,4], [10,1,20,3,40])
        # ENHANCE: add a toolbar
        # toolbar = NavigationToolbar(sc, self)
        # self.verticalLayout_plot = QtWidgets.QVBoxLayout()
        # self.verticalLayout_plot.addWidget(toolbar)
        # self.verticalLayout_plot.addWidget(sc)
        # self.horizontalLayout_4.addLayout(self.verticalLayout_plot)
        #
        self.horizontalLayout_4.addWidget(self.tracesPlt)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)

        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")

        ########################
        # Segmentation
        ########################
        sc = MplCanvas(self, width=5, height=4, dpi=100)
        self.segPlt = sc
        self.horizontalLayout_6.addWidget(self.segPlt)

        ########################
        # Red channel
        ########################
        sc = MplCanvas(self, width=5, height=4, dpi=100)
        self.redPlt = sc
        self.horizontalLayout_6.addWidget(self.redPlt)

        ########################
        # Green channel
        ########################
        sc = MplCanvas(self, width=5, height=4, dpi=100)
        self.greenPlt = sc
        self.horizontalLayout_6.addWidget(self.greenPlt)

        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        # self.menubar = QtWidgets.QMenuBar(MainWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 1084, 22))
        # self.menubar.setObjectName("menubar")
        # MainWindow.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(MainWindow)
        # self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.update_all_panels()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.neuronSelector.setItemText(0, _translate("MainWindow", "neuron0"))
        # self.tracesPlt.setText(_translate("MainWindow", "This is the very very large matplotlib \'label\' of the traces over time"))
        # self.segmentationImg.setText(_translate("MainWindow", "TextLabel"))
        # self.redChannelImg.setText(_translate("MainWindow", "TextLabel"))
        # self.greenChannelImg.setText(_translate("MainWindow", "TextLabel"))

    def update_all_panels(self):
        with safe_cd(self.project_dir):
            self.update_current_centroid()
            self.update_crop()
            self.update_only_traces()
            if not self.tracking_lost:
                self.update_segmentation()
                self.update_red()
                self.update_green()

    def update_only_traces(self):
        with safe_cd(self.project_dir):
            self.update_current_traces()
            self.update_traces_plot()

    def update_current_traces(self):
        mode = self.modeSelector.currentText()
        current_neuron = self.neuronSelector.currentText()
        if mode == 'green':
            y_raw = self.green_traces[current_neuron]['brightness']
            y = y_raw / self.green_traces[current_neuron]['volume']
            self.current_traces = y
        elif mode == 'red':
            y_raw = self.red_traces[current_neuron]['brightness']
            y = y_raw / self.red_traces[current_neuron]['volume']
            self.current_traces = y
        elif mode == 'ratio':
            red = self.red_traces[current_neuron]['brightness']
            green = self.green_traces[current_neuron]['brightness']
            back = self.background
            y = (red - back) / (green - back)
            self.current_traces = y
        else:
            print(f"Unknown mode ({mode})")
            raise NotImplementedError

    def update_traces_plot(self):
        mode = self.modeSelector.currentText()
        current_neuron = self.neuronSelector.currentText()
        y = self.current_traces
        # Vertical line for time
        t = self.timeSelector.value()
        ymin, ymax = np.min(y), np.max(y)
        # Actually plot
        canvas = self.tracesPlt.fig.canvas
        canvas.axes.cla()  # Clear the canvas.
        canvas.axes.plot(self.x, y, 'k')
        if not self.tracking_lost:
            z, x, y = self.current_centroid
            title = f"{current_neuron}: {mode} trace at ({z:.1f}, {x:.0f}, {y:.0f})"
            line_color = 'b'
        else:
            title = "Tracking lost!"
            line_color = 'r'
        canvas.axes.vlines(t, ymin, ymax, line_color)
        self.tracesPlt.axes.set_title(title)
        canvas.draw()

    def update_current_centroid(self):
        current_neuron = self.neuronSelector.currentText()
        t = self.timeSelector.value()
        # TODO: fix x-y switch
        z = self.red_traces[current_neuron]['z_dlc'].loc[t]
        x = self.red_traces[current_neuron]['x_dlc'].loc[t]
        y = self.red_traces[current_neuron]['y_dlc'].loc[t]
        if any([pd.isna(val) for val in [z, x, y]]):
            self.tracking_lost = True
            # Keep last centroid
        else:
            self.current_centroid = (z, x, y)
            self.tracking_lost = False

    def update_crop(self):
        x = self.cropXSelector.value()
        y = self.cropYSelector.value()
        self.crop_sz = (1, x, y)

    def update_segmentation(self):
        t = self.timeSelector.value()
        frame = self.seg_frame_factory(t, self.current_centroid)
        ax = self.segPlt.fig.canvas.axes
        ax.imshow(frame)
        title = "Segmentatation"  # at centroid {self.current_centroid}"
        ax.set_title(title)
        self.segPlt.fig.canvas.draw()

    def update_red(self):
        t = self.timeSelector.value()
        frame = self.red_frame_factory(t, self.current_centroid)
        ax = self.redPlt.fig.canvas.axes
        ax.imshow(frame)
        title = "Red Channel"
        ax.set_title(title)
        self.redPlt.fig.canvas.draw()

    def update_green(self):
        t = self.timeSelector.value()
        zxy = self.current_centroid
        frame = self.green_frame_factory(t, zxy)
        ax = self.greenPlt.fig.canvas.axes
        ax.imshow(frame)
        title = "Green Channel"
        ax.set_title(title)
        self.greenPlt.fig.canvas.draw()

    def red_frame_factory(self, t, zxy):
        fname = self.cfg['red_bigtiff_fname']
        num_slices = self.cfg['dataset_params']['num_slices']
        crop_frame = get_cropped_frame(fname, t, num_slices, zxy, self.crop_sz)
        return crop_frame

    def green_frame_factory(self, t, zxy):
        fname = self.cfg['green_bigtiff_fname']
        num_slices = self.cfg['dataset_params']['num_slices']
        sz = self.crop_sz
        to_flip = self.cfg['dataset_params']['red_and_green_mirrored']
        return get_cropped_frame(fname, t, num_slices, zxy, sz, to_flip)

    def seg_frame_factory(self, t, zxy):
        fname = self.segment_cfg['output']['masks']
        num_slices = self.cfg['dataset_params']['num_slices']
        t -= self.cfg['dataset_params']['start_volume']
        crop_frame = get_cropped_frame(fname, t, num_slices, zxy, self.crop_sz)
        return crop_frame


parser = argparse.ArgumentParser(description='Build GUI with a project')
parser.add_argument('project_config',
                    help='path to config file')
parser.add_argument('--DEBUG', default=False,
                    help='path to config file')

args = parser.parse_args()

if __name__ == "__main__":
    # Basic setup
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    # Get project settings
    project_config = args.project_config
    # Actually build window
    with safe_cd(Path(project_config).parent):
        ui.setupUi(MainWindow, project_config, args.DEBUG)
        MainWindow.show()
    sys.exit(app.exec_())
