# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_raw.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1084, 754)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.neuronSelector = QtWidgets.QComboBox(self.centralwidget)
        self.neuronSelector.setObjectName("neuronSelector")
        self.neuronSelector.addItem("")
        self.verticalLayout_5.addWidget(self.neuronSelector)
        self.timeSelector = QtWidgets.QSpinBox(self.centralwidget)
        self.timeSelector.setMinimum(100)
        self.timeSelector.setMaximum(600)
        self.timeSelector.setObjectName("timeSelector")
        self.verticalLayout_5.addWidget(self.timeSelector)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.tracesPlt = QtWidgets.QLabel(self.centralwidget)
        self.tracesPlt.setObjectName("tracesPlt")
        self.horizontalLayout_4.addWidget(self.tracesPlt)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.segmentationImg = QtWidgets.QLabel(self.centralwidget)
        self.segmentationImg.setObjectName("segmentationImg")
        self.horizontalLayout_6.addWidget(self.segmentationImg)
        self.redChannelImg = QtWidgets.QLabel(self.centralwidget)
        self.redChannelImg.setObjectName("redChannelImg")
        self.horizontalLayout_6.addWidget(self.redChannelImg)
        self.greenChannelImg = QtWidgets.QLabel(self.centralwidget)
        self.greenChannelImg.setObjectName("greenChannelImg")
        self.horizontalLayout_6.addWidget(self.greenChannelImg)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1084, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.neuronSelector.setItemText(0, _translate("MainWindow", "Neuron0"))
        self.tracesPlt.setText(_translate("MainWindow", "This is the very very large matplotlib \'label\' of the traces over time"))
        self.segmentationImg.setText(_translate("MainWindow", "TextLabel"))
        self.redChannelImg.setText(_translate("MainWindow", "TextLabel"))
        self.greenChannelImg.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
