configfile: "config.yaml"

rule all:
    input:
        expand("{tracklets}", tracklets=config['output_2']['tracklets'])

# Note: the files that I need to be there will not actually be passed directly, but will be read
rule step1:
    input:
        cfg=expand("{cfg}", cfg=config['project_path']),
        files=expand("{input_1}", input_1=config['input_1']),
        code_path=expand("{code}", code=config['code_path'])
    output:
        expand("{output_1}", output_1=config['output_1'])
    shell:
        "python {code_path}/1-segment_video.py with project_path={cfg}"


