# Example from: https://hackmd.io/@bluegenes/BJPrrj7WB
# cluster_config.yml - cluster configuration
# For the actual available resources, see the cluster documentation:
# https://lisc.univie.ac.at/wiki/content/working_environment/services/computational_resources

__default__:
    time: 0-6:00:00
    nodes: 1
    cpus_per_task: 16
    mem: 128G
    output: log_snakemake_step-%j.out
    mail_type: FAIL,TIME_LIMIT
    gres: # Should be empty

# Note: may need to push over to himem if the cluster is busy
preprocessing:
    time: 1-12:00:00
    mem: 120G
    cpus_per_task: 40

segmentation:
    time: 1-12:00:00
    mem: 256G
    cpus_per_task: 40

match_frame_pairs:
    gpus_per_node: 1
    time: 0-12:00:00
    mem: 128G
    gres: gpu:1

build_frame_objects:
    time: 0-12:00:00
    cpus_per_task: 20

postprocess_matches_to_tracklets:
    cpus_per_task: 1
    time: 0-2:00:00
    gres: gpu:1

combine_tracking_and_tracklets:
    time: 0-18:00:00
    cpus_per_task: 20

tracking:
    gpus_per_node: 1
    cpus_per_task: 16
    gres: gpu:1

barlow_tracking:
    gpus_per_node: 1
    cpus_per_task: 16
    gres: gpu:1

# Behavior
subtract_background:
    time: 0-08:00:00
    mem: 4G
    cpus_per_task: 8

tiff2avi:
    time: 0-18:00:00
    cpus_per_task: 2

dlc_analyze_videos:
    time: 0-08:00:00
    cpus_per_task: 24
    gres: gpu:1

create_centerline:
    time: 0-12:00:00
    mem: 8G
    cpus_per_task: 4

normalize_img:
    time: 0-06:00:00
    mem: 4G
    cpus_per_task: 8

worm_unet:
    time: 0-08:00:00
    cpus_per_task: 24
    gres: gpu:1

sam2_segment:
    time: 0-12:00:00  # Might be faster than this, needs testing
    cpus_per_task: 24
    gres: gpu:1

coil_unet:
    time: 0-08:00:00
    cpus_per_task: 24
    gres: gpu:1

binarize:
    time: 0-06:00:00
    cpus_per_task: 8
