# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'raw/create_project_raw.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import subprocess
import sys

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QFileDialog

from DLC_for_WBFM.gui.utils.file_dialog_widget import FileDialog


class CreateProjectDialog(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)

        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(9, 9, 781, 541))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout.addWidget(self.formLayoutWidget)

        self.projectLocationLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.projectLocationLabel.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.projectLocationLabel)
        self.project_foldername = None
        self.projectButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.projectButton.setObjectName("projectButton")
        self.projectButton.setText("Set Project Folder")
        self.projectButton.clicked.connect(self.load_project_foldername)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.projectButton)

        self.green_filename = None
        self.greenButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.greenButton.setObjectName("redButton")
        self.greenButton.setText("Load Green Dataset")
        self.greenButton.clicked.connect(self.load_green_filename)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.greenButton)
        self.greenLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.greenLabel.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.greenLabel)

        self.red_filename = None
        self.redButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.redButton.setObjectName("redButton")
        self.redButton.setText("Load Red Dataset")
        self.redButton.clicked.connect(self.load_red_filename)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.redButton)
        self.redLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.redLabel.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.redLabel)

        self.taskTextEdit = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.taskTextEdit.setObjectName("textEdit_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.taskTextEdit)
        self.taskLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.taskLabel.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.taskLabel)

        self.experimenterTextEdit = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.experimenterTextEdit.setObjectName("textEdit_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.experimenterTextEdit)
        self.experimenterLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.experimenterLabel.setObjectName("label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.experimenterLabel)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.finishButton = QtWidgets.QPushButton(self.centralwidget)
        self.finishButton.setObjectName("finishButton")
        self.finishButton.setText("Finish and create project")
        self.finishButton.clicked.connect(self.create_project)
        self.verticalLayout.addWidget(self.finishButton)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.projectLocationLabel.setText(_translate("MainWindow", "Project Location"))
        self.greenLabel.setText(_translate("MainWindow", "Dataset 1: Green channel"))
        self.redLabel.setText(_translate("MainWindow", "Dataset 2: Red channel"))
        self.taskLabel.setText(_translate("MainWindow", "Task Name (optional)"))
        self.experimenterLabel.setText(_translate("MainWindow", "Experimenter"))

    def load_red_filename(self):
        ex = FileDialog()
        self.red_filename = ex.fileName
        self.redLabel.setText(self.red_filename)

    def load_green_filename(self):
        ex = FileDialog()
        self.green_filename = ex.fileName
        self.greenLabel.setText(self.green_filename)

    def load_project_foldername(self):
        ex = FileDialog(file_not_folder=False)
        self.project_foldername = ex.fileName
        self.projectLocationLabel.setText(self.project_foldername)

    def create_project(self):
        if self.red_filename is not None and \
            self.green_filename is not None and \
            self.project_foldername is not None:
            # TODO: don't just call python from python!
            COMMAND = "scripts/0-create_new_project.py"
            EXPERIMENTER = self.experimenterTextEdit.toPlainText()
            TASK = self.taskTextEdit.toPlainText()
            subprocess.run(f"python {COMMAND} with project_dir={self.project_foldername} red_bigtiff_fname={self.red_filename} green_bigtiff_fname={self.green_filename} experimenter={EXPERIMENTER} task_name={TASK}")

            self.finishButton.setText("Create new project; Close the window if finished")
        else:
            print("Fill out required fields first!")

if __name__ == '__main__':
    # Basic setup
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = CreateProjectDialog()
    # Actually build window
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
